#!/bin/bash
#SBATCH -D /home/jolyang/Documents/Github/N2
#SBATCH -o /home/jolyang/Documents/Github/N2/slurm-log/testout-%j.txt
#SBATCH -e /home/jolyang/Documents/Github/N2/slurm-log/err-%j.txt
#SBATCH -J run_hapmix1.sh
#SBATCH--mail-user=yangjl0930@gmail.com
#SBATCH--mail-type=END
#SBATCH--mail-type=FAIL #email if fails
set -e
set -u

cd largedata/hapmixrun1
perl bin/runHapmix.pl hprun_gen10_chr1.par
perl bin/runHapmix.pl hprun_gen10_chr2.par
perl bin/runHapmix.pl hprun_gen10_chr3.par
perl bin/runHapmix.pl hprun_gen10_chr4.par
perl bin/runHapmix.pl hprun_gen10_chr5.par
perl bin/runHapmix.pl hprun_gen10_chr6.par
perl bin/runHapmix.pl hprun_gen10_chr7.par
perl bin/runHapmix.pl hprun_gen10_chr8.par
perl bin/runHapmix.pl hprun_gen10_chr9.par
perl bin/runHapmix.pl hprun_gen10_chr10.par
perl bin/runHapmix.pl hprun_gen20_chr1.par
perl bin/runHapmix.pl hprun_gen20_chr2.par
perl bin/runHapmix.pl hprun_gen20_chr3.par
perl bin/runHapmix.pl hprun_gen20_chr4.par
perl bin/runHapmix.pl hprun_gen20_chr5.par
perl bin/runHapmix.pl hprun_gen20_chr6.par
perl bin/runHapmix.pl hprun_gen20_chr7.par
perl bin/runHapmix.pl hprun_gen20_chr8.par
perl bin/runHapmix.pl hprun_gen20_chr9.par
perl bin/runHapmix.pl hprun_gen20_chr10.par
perl bin/runHapmix.pl hprun_gen30_chr1.par
perl bin/runHapmix.pl hprun_gen30_chr2.par
perl bin/runHapmix.pl hprun_gen30_chr3.par
perl bin/runHapmix.pl hprun_gen30_chr4.par
perl bin/runHapmix.pl hprun_gen30_chr5.par
perl bin/runHapmix.pl hprun_gen30_chr6.par
perl bin/runHapmix.pl hprun_gen30_chr7.par
perl bin/runHapmix.pl hprun_gen30_chr8.par
perl bin/runHapmix.pl hprun_gen30_chr9.par
perl bin/runHapmix.pl hprun_gen30_chr10.par
perl bin/runHapmix.pl hprun_gen40_chr1.par
perl bin/runHapmix.pl hprun_gen40_chr2.par
perl bin/runHapmix.pl hprun_gen40_chr3.par
perl bin/runHapmix.pl hprun_gen40_chr4.par
perl bin/runHapmix.pl hprun_gen40_chr5.par
perl bin/runHapmix.pl hprun_gen40_chr6.par
perl bin/runHapmix.pl hprun_gen40_chr7.par
perl bin/runHapmix.pl hprun_gen40_chr8.par
perl bin/runHapmix.pl hprun_gen40_chr9.par
perl bin/runHapmix.pl hprun_gen40_chr10.par
perl bin/runHapmix.pl hprun_gen50_chr1.par
perl bin/runHapmix.pl hprun_gen50_chr2.par
perl bin/runHapmix.pl hprun_gen50_chr3.par
perl bin/runHapmix.pl hprun_gen50_chr4.par
perl bin/runHapmix.pl hprun_gen50_chr5.par
perl bin/runHapmix.pl hprun_gen50_chr6.par
perl bin/runHapmix.pl hprun_gen50_chr7.par
perl bin/runHapmix.pl hprun_gen50_chr8.par
perl bin/runHapmix.pl hprun_gen50_chr9.par
perl bin/runHapmix.pl hprun_gen50_chr10.par
perl bin/runHapmix.pl hprun_gen60_chr1.par
perl bin/runHapmix.pl hprun_gen60_chr2.par
perl bin/runHapmix.pl hprun_gen60_chr3.par
perl bin/runHapmix.pl hprun_gen60_chr4.par
perl bin/runHapmix.pl hprun_gen60_chr5.par
perl bin/runHapmix.pl hprun_gen60_chr6.par
perl bin/runHapmix.pl hprun_gen60_chr7.par
perl bin/runHapmix.pl hprun_gen60_chr8.par
perl bin/runHapmix.pl hprun_gen60_chr9.par
perl bin/runHapmix.pl hprun_gen60_chr10.par
perl bin/runHapmix.pl hprun_gen70_chr1.par
perl bin/runHapmix.pl hprun_gen70_chr2.par
perl bin/runHapmix.pl hprun_gen70_chr3.par
perl bin/runHapmix.pl hprun_gen70_chr4.par
perl bin/runHapmix.pl hprun_gen70_chr5.par
perl bin/runHapmix.pl hprun_gen70_chr6.par
perl bin/runHapmix.pl hprun_gen70_chr7.par
perl bin/runHapmix.pl hprun_gen70_chr8.par
perl bin/runHapmix.pl hprun_gen70_chr9.par
perl bin/runHapmix.pl hprun_gen70_chr10.par
perl bin/runHapmix.pl hprun_gen80_chr1.par
perl bin/runHapmix.pl hprun_gen80_chr2.par
perl bin/runHapmix.pl hprun_gen80_chr3.par
perl bin/runHapmix.pl hprun_gen80_chr4.par
perl bin/runHapmix.pl hprun_gen80_chr5.par
perl bin/runHapmix.pl hprun_gen80_chr6.par
perl bin/runHapmix.pl hprun_gen80_chr7.par
perl bin/runHapmix.pl hprun_gen80_chr8.par
perl bin/runHapmix.pl hprun_gen80_chr9.par
perl bin/runHapmix.pl hprun_gen80_chr10.par
perl bin/runHapmix.pl hprun_gen90_chr1.par
perl bin/runHapmix.pl hprun_gen90_chr2.par
perl bin/runHapmix.pl hprun_gen90_chr3.par
perl bin/runHapmix.pl hprun_gen90_chr4.par
perl bin/runHapmix.pl hprun_gen90_chr5.par
perl bin/runHapmix.pl hprun_gen90_chr6.par
perl bin/runHapmix.pl hprun_gen90_chr7.par
perl bin/runHapmix.pl hprun_gen90_chr8.par
perl bin/runHapmix.pl hprun_gen90_chr9.par
perl bin/runHapmix.pl hprun_gen90_chr10.par
perl bin/runHapmix.pl hprun_gen100_chr1.par
perl bin/runHapmix.pl hprun_gen100_chr2.par
perl bin/runHapmix.pl hprun_gen100_chr3.par
perl bin/runHapmix.pl hprun_gen100_chr4.par
perl bin/runHapmix.pl hprun_gen100_chr5.par
perl bin/runHapmix.pl hprun_gen100_chr6.par
perl bin/runHapmix.pl hprun_gen100_chr7.par
perl bin/runHapmix.pl hprun_gen100_chr8.par
perl bin/runHapmix.pl hprun_gen100_chr9.par
perl bin/runHapmix.pl hprun_gen100_chr10.par
perl bin/runHapmix.pl hprun_gen110_chr1.par
perl bin/runHapmix.pl hprun_gen110_chr2.par
perl bin/runHapmix.pl hprun_gen110_chr3.par
perl bin/runHapmix.pl hprun_gen110_chr4.par
perl bin/runHapmix.pl hprun_gen110_chr5.par
perl bin/runHapmix.pl hprun_gen110_chr6.par
perl bin/runHapmix.pl hprun_gen110_chr7.par
perl bin/runHapmix.pl hprun_gen110_chr8.par
perl bin/runHapmix.pl hprun_gen110_chr9.par
perl bin/runHapmix.pl hprun_gen110_chr10.par
perl bin/runHapmix.pl hprun_gen120_chr1.par
perl bin/runHapmix.pl hprun_gen120_chr2.par
perl bin/runHapmix.pl hprun_gen120_chr3.par
perl bin/runHapmix.pl hprun_gen120_chr4.par
perl bin/runHapmix.pl hprun_gen120_chr5.par
perl bin/runHapmix.pl hprun_gen120_chr6.par
perl bin/runHapmix.pl hprun_gen120_chr7.par
perl bin/runHapmix.pl hprun_gen120_chr8.par
perl bin/runHapmix.pl hprun_gen120_chr9.par
perl bin/runHapmix.pl hprun_gen120_chr10.par
perl bin/runHapmix.pl hprun_gen130_chr1.par
perl bin/runHapmix.pl hprun_gen130_chr2.par
perl bin/runHapmix.pl hprun_gen130_chr3.par
perl bin/runHapmix.pl hprun_gen130_chr4.par
perl bin/runHapmix.pl hprun_gen130_chr5.par
perl bin/runHapmix.pl hprun_gen130_chr6.par
perl bin/runHapmix.pl hprun_gen130_chr7.par
perl bin/runHapmix.pl hprun_gen130_chr8.par
perl bin/runHapmix.pl hprun_gen130_chr9.par
perl bin/runHapmix.pl hprun_gen130_chr10.par
perl bin/runHapmix.pl hprun_gen140_chr1.par
perl bin/runHapmix.pl hprun_gen140_chr2.par
perl bin/runHapmix.pl hprun_gen140_chr3.par
perl bin/runHapmix.pl hprun_gen140_chr4.par
perl bin/runHapmix.pl hprun_gen140_chr5.par
perl bin/runHapmix.pl hprun_gen140_chr6.par
perl bin/runHapmix.pl hprun_gen140_chr7.par
perl bin/runHapmix.pl hprun_gen140_chr8.par
perl bin/runHapmix.pl hprun_gen140_chr9.par
perl bin/runHapmix.pl hprun_gen140_chr10.par
perl bin/runHapmix.pl hprun_gen150_chr1.par
perl bin/runHapmix.pl hprun_gen150_chr2.par
perl bin/runHapmix.pl hprun_gen150_chr3.par
perl bin/runHapmix.pl hprun_gen150_chr4.par
perl bin/runHapmix.pl hprun_gen150_chr5.par
perl bin/runHapmix.pl hprun_gen150_chr6.par
perl bin/runHapmix.pl hprun_gen150_chr7.par
perl bin/runHapmix.pl hprun_gen150_chr8.par
perl bin/runHapmix.pl hprun_gen150_chr9.par
perl bin/runHapmix.pl hprun_gen150_chr10.par
perl bin/runHapmix.pl hprun_gen160_chr1.par
perl bin/runHapmix.pl hprun_gen160_chr2.par
perl bin/runHapmix.pl hprun_gen160_chr3.par
perl bin/runHapmix.pl hprun_gen160_chr4.par
perl bin/runHapmix.pl hprun_gen160_chr5.par
perl bin/runHapmix.pl hprun_gen160_chr6.par
perl bin/runHapmix.pl hprun_gen160_chr7.par
perl bin/runHapmix.pl hprun_gen160_chr8.par
perl bin/runHapmix.pl hprun_gen160_chr9.par
perl bin/runHapmix.pl hprun_gen160_chr10.par
perl bin/runHapmix.pl hprun_gen170_chr1.par
perl bin/runHapmix.pl hprun_gen170_chr2.par
perl bin/runHapmix.pl hprun_gen170_chr3.par
perl bin/runHapmix.pl hprun_gen170_chr4.par
perl bin/runHapmix.pl hprun_gen170_chr5.par
perl bin/runHapmix.pl hprun_gen170_chr6.par
perl bin/runHapmix.pl hprun_gen170_chr7.par
perl bin/runHapmix.pl hprun_gen170_chr8.par
perl bin/runHapmix.pl hprun_gen170_chr9.par
perl bin/runHapmix.pl hprun_gen170_chr10.par
perl bin/runHapmix.pl hprun_gen180_chr1.par
perl bin/runHapmix.pl hprun_gen180_chr2.par
perl bin/runHapmix.pl hprun_gen180_chr3.par
perl bin/runHapmix.pl hprun_gen180_chr4.par
perl bin/runHapmix.pl hprun_gen180_chr5.par
perl bin/runHapmix.pl hprun_gen180_chr6.par
perl bin/runHapmix.pl hprun_gen180_chr7.par
perl bin/runHapmix.pl hprun_gen180_chr8.par
perl bin/runHapmix.pl hprun_gen180_chr9.par
perl bin/runHapmix.pl hprun_gen180_chr10.par
perl bin/runHapmix.pl hprun_gen190_chr1.par
perl bin/runHapmix.pl hprun_gen190_chr2.par
perl bin/runHapmix.pl hprun_gen190_chr3.par
perl bin/runHapmix.pl hprun_gen190_chr4.par
perl bin/runHapmix.pl hprun_gen190_chr5.par
perl bin/runHapmix.pl hprun_gen190_chr6.par
perl bin/runHapmix.pl hprun_gen190_chr7.par
perl bin/runHapmix.pl hprun_gen190_chr8.par
perl bin/runHapmix.pl hprun_gen190_chr9.par
perl bin/runHapmix.pl hprun_gen190_chr10.par
perl bin/runHapmix.pl hprun_gen200_chr1.par
perl bin/runHapmix.pl hprun_gen200_chr2.par
perl bin/runHapmix.pl hprun_gen200_chr3.par
perl bin/runHapmix.pl hprun_gen200_chr4.par
perl bin/runHapmix.pl hprun_gen200_chr5.par
perl bin/runHapmix.pl hprun_gen200_chr6.par
perl bin/runHapmix.pl hprun_gen200_chr7.par
perl bin/runHapmix.pl hprun_gen200_chr8.par
perl bin/runHapmix.pl hprun_gen200_chr9.par
perl bin/runHapmix.pl hprun_gen200_chr10.par
perl bin/runHapmix.pl hprun_gen210_chr1.par
perl bin/runHapmix.pl hprun_gen210_chr2.par
perl bin/runHapmix.pl hprun_gen210_chr3.par
perl bin/runHapmix.pl hprun_gen210_chr4.par
perl bin/runHapmix.pl hprun_gen210_chr5.par
perl bin/runHapmix.pl hprun_gen210_chr6.par
perl bin/runHapmix.pl hprun_gen210_chr7.par
perl bin/runHapmix.pl hprun_gen210_chr8.par
perl bin/runHapmix.pl hprun_gen210_chr9.par
perl bin/runHapmix.pl hprun_gen210_chr10.par
perl bin/runHapmix.pl hprun_gen220_chr1.par
perl bin/runHapmix.pl hprun_gen220_chr2.par
perl bin/runHapmix.pl hprun_gen220_chr3.par
perl bin/runHapmix.pl hprun_gen220_chr4.par
perl bin/runHapmix.pl hprun_gen220_chr5.par
perl bin/runHapmix.pl hprun_gen220_chr6.par
perl bin/runHapmix.pl hprun_gen220_chr7.par
perl bin/runHapmix.pl hprun_gen220_chr8.par
perl bin/runHapmix.pl hprun_gen220_chr9.par
perl bin/runHapmix.pl hprun_gen220_chr10.par
perl bin/runHapmix.pl hprun_gen230_chr1.par
perl bin/runHapmix.pl hprun_gen230_chr2.par
perl bin/runHapmix.pl hprun_gen230_chr3.par
perl bin/runHapmix.pl hprun_gen230_chr4.par
perl bin/runHapmix.pl hprun_gen230_chr5.par
perl bin/runHapmix.pl hprun_gen230_chr6.par
perl bin/runHapmix.pl hprun_gen230_chr7.par
perl bin/runHapmix.pl hprun_gen230_chr8.par
perl bin/runHapmix.pl hprun_gen230_chr9.par
perl bin/runHapmix.pl hprun_gen230_chr10.par
perl bin/runHapmix.pl hprun_gen240_chr1.par
perl bin/runHapmix.pl hprun_gen240_chr2.par
perl bin/runHapmix.pl hprun_gen240_chr3.par
perl bin/runHapmix.pl hprun_gen240_chr4.par
perl bin/runHapmix.pl hprun_gen240_chr5.par
perl bin/runHapmix.pl hprun_gen240_chr6.par
perl bin/runHapmix.pl hprun_gen240_chr7.par
perl bin/runHapmix.pl hprun_gen240_chr8.par
perl bin/runHapmix.pl hprun_gen240_chr9.par
perl bin/runHapmix.pl hprun_gen240_chr10.par
perl bin/runHapmix.pl hprun_gen250_chr1.par
perl bin/runHapmix.pl hprun_gen250_chr2.par
perl bin/runHapmix.pl hprun_gen250_chr3.par
perl bin/runHapmix.pl hprun_gen250_chr4.par
perl bin/runHapmix.pl hprun_gen250_chr5.par
perl bin/runHapmix.pl hprun_gen250_chr6.par
perl bin/runHapmix.pl hprun_gen250_chr7.par
perl bin/runHapmix.pl hprun_gen250_chr8.par
perl bin/runHapmix.pl hprun_gen250_chr9.par
perl bin/runHapmix.pl hprun_gen250_chr10.par
perl bin/runHapmix.pl hprun_gen260_chr1.par
perl bin/runHapmix.pl hprun_gen260_chr2.par
perl bin/runHapmix.pl hprun_gen260_chr3.par
perl bin/runHapmix.pl hprun_gen260_chr4.par
perl bin/runHapmix.pl hprun_gen260_chr5.par
perl bin/runHapmix.pl hprun_gen260_chr6.par
perl bin/runHapmix.pl hprun_gen260_chr7.par
perl bin/runHapmix.pl hprun_gen260_chr8.par
perl bin/runHapmix.pl hprun_gen260_chr9.par
perl bin/runHapmix.pl hprun_gen260_chr10.par
perl bin/runHapmix.pl hprun_gen270_chr1.par
perl bin/runHapmix.pl hprun_gen270_chr2.par
perl bin/runHapmix.pl hprun_gen270_chr3.par
perl bin/runHapmix.pl hprun_gen270_chr4.par
perl bin/runHapmix.pl hprun_gen270_chr5.par
perl bin/runHapmix.pl hprun_gen270_chr6.par
perl bin/runHapmix.pl hprun_gen270_chr7.par
perl bin/runHapmix.pl hprun_gen270_chr8.par
perl bin/runHapmix.pl hprun_gen270_chr9.par
perl bin/runHapmix.pl hprun_gen270_chr10.par
perl bin/runHapmix.pl hprun_gen280_chr1.par
perl bin/runHapmix.pl hprun_gen280_chr2.par
perl bin/runHapmix.pl hprun_gen280_chr3.par
perl bin/runHapmix.pl hprun_gen280_chr4.par
perl bin/runHapmix.pl hprun_gen280_chr5.par
perl bin/runHapmix.pl hprun_gen280_chr6.par
perl bin/runHapmix.pl hprun_gen280_chr7.par
perl bin/runHapmix.pl hprun_gen280_chr8.par
perl bin/runHapmix.pl hprun_gen280_chr9.par
perl bin/runHapmix.pl hprun_gen280_chr10.par
perl bin/runHapmix.pl hprun_gen290_chr1.par
perl bin/runHapmix.pl hprun_gen290_chr2.par
perl bin/runHapmix.pl hprun_gen290_chr3.par
perl bin/runHapmix.pl hprun_gen290_chr4.par
perl bin/runHapmix.pl hprun_gen290_chr5.par
perl bin/runHapmix.pl hprun_gen290_chr6.par
perl bin/runHapmix.pl hprun_gen290_chr7.par
perl bin/runHapmix.pl hprun_gen290_chr8.par
perl bin/runHapmix.pl hprun_gen290_chr9.par
perl bin/runHapmix.pl hprun_gen290_chr10.par
perl bin/runHapmix.pl hprun_gen300_chr1.par
perl bin/runHapmix.pl hprun_gen300_chr2.par
perl bin/runHapmix.pl hprun_gen300_chr3.par
perl bin/runHapmix.pl hprun_gen300_chr4.par
perl bin/runHapmix.pl hprun_gen300_chr5.par
perl bin/runHapmix.pl hprun_gen300_chr6.par
perl bin/runHapmix.pl hprun_gen300_chr7.par
perl bin/runHapmix.pl hprun_gen300_chr8.par
perl bin/runHapmix.pl hprun_gen300_chr9.par
perl bin/runHapmix.pl hprun_gen300_chr10.par
perl bin/runHapmix.pl hprun_gen310_chr1.par
perl bin/runHapmix.pl hprun_gen310_chr2.par
perl bin/runHapmix.pl hprun_gen310_chr3.par
perl bin/runHapmix.pl hprun_gen310_chr4.par
perl bin/runHapmix.pl hprun_gen310_chr5.par
perl bin/runHapmix.pl hprun_gen310_chr6.par
perl bin/runHapmix.pl hprun_gen310_chr7.par
perl bin/runHapmix.pl hprun_gen310_chr8.par
perl bin/runHapmix.pl hprun_gen310_chr9.par
perl bin/runHapmix.pl hprun_gen310_chr10.par
perl bin/runHapmix.pl hprun_gen320_chr1.par
perl bin/runHapmix.pl hprun_gen320_chr2.par
perl bin/runHapmix.pl hprun_gen320_chr3.par
perl bin/runHapmix.pl hprun_gen320_chr4.par
perl bin/runHapmix.pl hprun_gen320_chr5.par
perl bin/runHapmix.pl hprun_gen320_chr6.par
perl bin/runHapmix.pl hprun_gen320_chr7.par
perl bin/runHapmix.pl hprun_gen320_chr8.par
perl bin/runHapmix.pl hprun_gen320_chr9.par
perl bin/runHapmix.pl hprun_gen320_chr10.par
perl bin/runHapmix.pl hprun_gen330_chr1.par
perl bin/runHapmix.pl hprun_gen330_chr2.par
perl bin/runHapmix.pl hprun_gen330_chr3.par
perl bin/runHapmix.pl hprun_gen330_chr4.par
perl bin/runHapmix.pl hprun_gen330_chr5.par
perl bin/runHapmix.pl hprun_gen330_chr6.par
perl bin/runHapmix.pl hprun_gen330_chr7.par
perl bin/runHapmix.pl hprun_gen330_chr8.par
perl bin/runHapmix.pl hprun_gen330_chr9.par
perl bin/runHapmix.pl hprun_gen330_chr10.par
perl bin/runHapmix.pl hprun_gen340_chr1.par
perl bin/runHapmix.pl hprun_gen340_chr2.par
perl bin/runHapmix.pl hprun_gen340_chr3.par
perl bin/runHapmix.pl hprun_gen340_chr4.par
perl bin/runHapmix.pl hprun_gen340_chr5.par
perl bin/runHapmix.pl hprun_gen340_chr6.par
perl bin/runHapmix.pl hprun_gen340_chr7.par
perl bin/runHapmix.pl hprun_gen340_chr8.par
perl bin/runHapmix.pl hprun_gen340_chr9.par
perl bin/runHapmix.pl hprun_gen340_chr10.par
perl bin/runHapmix.pl hprun_gen350_chr1.par
perl bin/runHapmix.pl hprun_gen350_chr2.par
perl bin/runHapmix.pl hprun_gen350_chr3.par
perl bin/runHapmix.pl hprun_gen350_chr4.par
perl bin/runHapmix.pl hprun_gen350_chr5.par
perl bin/runHapmix.pl hprun_gen350_chr6.par
perl bin/runHapmix.pl hprun_gen350_chr7.par
perl bin/runHapmix.pl hprun_gen350_chr8.par
perl bin/runHapmix.pl hprun_gen350_chr9.par
perl bin/runHapmix.pl hprun_gen350_chr10.par
perl bin/runHapmix.pl hprun_gen360_chr1.par
perl bin/runHapmix.pl hprun_gen360_chr2.par
perl bin/runHapmix.pl hprun_gen360_chr3.par
perl bin/runHapmix.pl hprun_gen360_chr4.par
perl bin/runHapmix.pl hprun_gen360_chr5.par
perl bin/runHapmix.pl hprun_gen360_chr6.par
perl bin/runHapmix.pl hprun_gen360_chr7.par
perl bin/runHapmix.pl hprun_gen360_chr8.par
perl bin/runHapmix.pl hprun_gen360_chr9.par
perl bin/runHapmix.pl hprun_gen360_chr10.par
perl bin/runHapmix.pl hprun_gen370_chr1.par
perl bin/runHapmix.pl hprun_gen370_chr2.par
perl bin/runHapmix.pl hprun_gen370_chr3.par
perl bin/runHapmix.pl hprun_gen370_chr4.par
perl bin/runHapmix.pl hprun_gen370_chr5.par
perl bin/runHapmix.pl hprun_gen370_chr6.par
perl bin/runHapmix.pl hprun_gen370_chr7.par
perl bin/runHapmix.pl hprun_gen370_chr8.par
perl bin/runHapmix.pl hprun_gen370_chr9.par
perl bin/runHapmix.pl hprun_gen370_chr10.par
perl bin/runHapmix.pl hprun_gen380_chr1.par
perl bin/runHapmix.pl hprun_gen380_chr2.par
perl bin/runHapmix.pl hprun_gen380_chr3.par
perl bin/runHapmix.pl hprun_gen380_chr4.par
perl bin/runHapmix.pl hprun_gen380_chr5.par
perl bin/runHapmix.pl hprun_gen380_chr6.par
perl bin/runHapmix.pl hprun_gen380_chr7.par
perl bin/runHapmix.pl hprun_gen380_chr8.par
perl bin/runHapmix.pl hprun_gen380_chr9.par
perl bin/runHapmix.pl hprun_gen380_chr10.par
perl bin/runHapmix.pl hprun_gen390_chr1.par
perl bin/runHapmix.pl hprun_gen390_chr2.par
perl bin/runHapmix.pl hprun_gen390_chr3.par
perl bin/runHapmix.pl hprun_gen390_chr4.par
perl bin/runHapmix.pl hprun_gen390_chr5.par
perl bin/runHapmix.pl hprun_gen390_chr6.par
perl bin/runHapmix.pl hprun_gen390_chr7.par
perl bin/runHapmix.pl hprun_gen390_chr8.par
perl bin/runHapmix.pl hprun_gen390_chr9.par
perl bin/runHapmix.pl hprun_gen390_chr10.par
perl bin/runHapmix.pl hprun_gen400_chr1.par
perl bin/runHapmix.pl hprun_gen400_chr2.par
perl bin/runHapmix.pl hprun_gen400_chr3.par
perl bin/runHapmix.pl hprun_gen400_chr4.par
perl bin/runHapmix.pl hprun_gen400_chr5.par
perl bin/runHapmix.pl hprun_gen400_chr6.par
perl bin/runHapmix.pl hprun_gen400_chr7.par
perl bin/runHapmix.pl hprun_gen400_chr8.par
perl bin/runHapmix.pl hprun_gen400_chr9.par
perl bin/runHapmix.pl hprun_gen400_chr10.par
perl bin/runHapmix.pl hprun_gen410_chr1.par
perl bin/runHapmix.pl hprun_gen410_chr2.par
perl bin/runHapmix.pl hprun_gen410_chr3.par
perl bin/runHapmix.pl hprun_gen410_chr4.par
perl bin/runHapmix.pl hprun_gen410_chr5.par
perl bin/runHapmix.pl hprun_gen410_chr6.par
perl bin/runHapmix.pl hprun_gen410_chr7.par
perl bin/runHapmix.pl hprun_gen410_chr8.par
perl bin/runHapmix.pl hprun_gen410_chr9.par
perl bin/runHapmix.pl hprun_gen410_chr10.par
perl bin/runHapmix.pl hprun_gen420_chr1.par
perl bin/runHapmix.pl hprun_gen420_chr2.par
perl bin/runHapmix.pl hprun_gen420_chr3.par
perl bin/runHapmix.pl hprun_gen420_chr4.par
perl bin/runHapmix.pl hprun_gen420_chr5.par
perl bin/runHapmix.pl hprun_gen420_chr6.par
perl bin/runHapmix.pl hprun_gen420_chr7.par
perl bin/runHapmix.pl hprun_gen420_chr8.par
perl bin/runHapmix.pl hprun_gen420_chr9.par
perl bin/runHapmix.pl hprun_gen420_chr10.par
perl bin/runHapmix.pl hprun_gen430_chr1.par
perl bin/runHapmix.pl hprun_gen430_chr2.par
perl bin/runHapmix.pl hprun_gen430_chr3.par
perl bin/runHapmix.pl hprun_gen430_chr4.par
perl bin/runHapmix.pl hprun_gen430_chr5.par
perl bin/runHapmix.pl hprun_gen430_chr6.par
perl bin/runHapmix.pl hprun_gen430_chr7.par
perl bin/runHapmix.pl hprun_gen430_chr8.par
perl bin/runHapmix.pl hprun_gen430_chr9.par
perl bin/runHapmix.pl hprun_gen430_chr10.par
perl bin/runHapmix.pl hprun_gen440_chr1.par
perl bin/runHapmix.pl hprun_gen440_chr2.par
perl bin/runHapmix.pl hprun_gen440_chr3.par
perl bin/runHapmix.pl hprun_gen440_chr4.par
perl bin/runHapmix.pl hprun_gen440_chr5.par
perl bin/runHapmix.pl hprun_gen440_chr6.par
perl bin/runHapmix.pl hprun_gen440_chr7.par
perl bin/runHapmix.pl hprun_gen440_chr8.par
perl bin/runHapmix.pl hprun_gen440_chr9.par
perl bin/runHapmix.pl hprun_gen440_chr10.par
perl bin/runHapmix.pl hprun_gen450_chr1.par
perl bin/runHapmix.pl hprun_gen450_chr2.par
perl bin/runHapmix.pl hprun_gen450_chr3.par
perl bin/runHapmix.pl hprun_gen450_chr4.par
perl bin/runHapmix.pl hprun_gen450_chr5.par
perl bin/runHapmix.pl hprun_gen450_chr6.par
perl bin/runHapmix.pl hprun_gen450_chr7.par
perl bin/runHapmix.pl hprun_gen450_chr8.par
perl bin/runHapmix.pl hprun_gen450_chr9.par
perl bin/runHapmix.pl hprun_gen450_chr10.par
perl bin/runHapmix.pl hprun_gen460_chr1.par
perl bin/runHapmix.pl hprun_gen460_chr2.par
perl bin/runHapmix.pl hprun_gen460_chr3.par
perl bin/runHapmix.pl hprun_gen460_chr4.par
perl bin/runHapmix.pl hprun_gen460_chr5.par
perl bin/runHapmix.pl hprun_gen460_chr6.par
perl bin/runHapmix.pl hprun_gen460_chr7.par
perl bin/runHapmix.pl hprun_gen460_chr8.par
perl bin/runHapmix.pl hprun_gen460_chr9.par
perl bin/runHapmix.pl hprun_gen460_chr10.par
perl bin/runHapmix.pl hprun_gen470_chr1.par
perl bin/runHapmix.pl hprun_gen470_chr2.par
perl bin/runHapmix.pl hprun_gen470_chr3.par
perl bin/runHapmix.pl hprun_gen470_chr4.par
perl bin/runHapmix.pl hprun_gen470_chr5.par
perl bin/runHapmix.pl hprun_gen470_chr6.par
perl bin/runHapmix.pl hprun_gen470_chr7.par
perl bin/runHapmix.pl hprun_gen470_chr8.par
perl bin/runHapmix.pl hprun_gen470_chr9.par
perl bin/runHapmix.pl hprun_gen470_chr10.par
perl bin/runHapmix.pl hprun_gen480_chr1.par
perl bin/runHapmix.pl hprun_gen480_chr2.par
perl bin/runHapmix.pl hprun_gen480_chr3.par
perl bin/runHapmix.pl hprun_gen480_chr4.par
perl bin/runHapmix.pl hprun_gen480_chr5.par
perl bin/runHapmix.pl hprun_gen480_chr6.par
perl bin/runHapmix.pl hprun_gen480_chr7.par
perl bin/runHapmix.pl hprun_gen480_chr8.par
perl bin/runHapmix.pl hprun_gen480_chr9.par
perl bin/runHapmix.pl hprun_gen480_chr10.par
perl bin/runHapmix.pl hprun_gen490_chr1.par
perl bin/runHapmix.pl hprun_gen490_chr2.par
perl bin/runHapmix.pl hprun_gen490_chr3.par
perl bin/runHapmix.pl hprun_gen490_chr4.par
perl bin/runHapmix.pl hprun_gen490_chr5.par
perl bin/runHapmix.pl hprun_gen490_chr6.par
perl bin/runHapmix.pl hprun_gen490_chr7.par
perl bin/runHapmix.pl hprun_gen490_chr8.par
perl bin/runHapmix.pl hprun_gen490_chr9.par
perl bin/runHapmix.pl hprun_gen490_chr10.par
perl bin/runHapmix.pl hprun_gen500_chr1.par
perl bin/runHapmix.pl hprun_gen500_chr2.par
perl bin/runHapmix.pl hprun_gen500_chr3.par
perl bin/runHapmix.pl hprun_gen500_chr4.par
perl bin/runHapmix.pl hprun_gen500_chr5.par
perl bin/runHapmix.pl hprun_gen500_chr6.par
perl bin/runHapmix.pl hprun_gen500_chr7.par
perl bin/runHapmix.pl hprun_gen500_chr8.par
perl bin/runHapmix.pl hprun_gen500_chr9.par
perl bin/runHapmix.pl hprun_gen500_chr10.par
